### ISSUE TITLE
bug: command create work cannot create correct manifest work

### ISSUE THREAD

**Issue by ycyaoxdu** [open-cluster-management-io/clusteradm#162]
deploy in managedcluster create failed while i create a work using clusteradm 
```
status:
  conditions:
  - lastTransitionTime: "2022-03-18T03:28:21Z"
    message: 1 of 1 resources have unknown status
    observedGeneration: 1
    reason: ResourcesStatusUnknown
    status: Unknown
    type: Available
  - lastTransitionTime: "2022-03-18T03:28:21Z"
    message: Failed to apply manifest work
    observedGeneration: 1
    reason: AppliedManifestWorkFailed
    status: "False"
    type: Applied
  resourceStatus:
    manifests:
    - conditions:
      - lastTransitionTime: "2022-03-18T03:28:21Z"
        message: 'Failed to apply manifest: cluster1 "hello-work-demo" is forbidden:
          User "system:serviceaccount:open-cluster-management-agent:klusterlet-work-sa"
          cannot get resource "cluster1" in API group "" at the cluster scope'
        reason: AppliedManifestFailed
        status: "False"
        type: Applied
      - lastTransitionTime: "2022-03-18T03:28:21Z"
        message: Resource meta is incompleted
        reason: IncompletedResourceMeta
        status: Unknown
        type: Available
      resourceMeta:
        group: work.open-cluster-management.io
        kind: ManifestWork
        name: hello-work-demo
        namespace: cluster1
        ordinal: 0
        resource: ""
        version: v1
      statusFeedback: {}
```

**Comment by qiujian16** [comment]
we might need to better document here. The manifest is not to be `ManifestWork`, but a manifest files containing legacy kube resources.

**Comment by ycyaoxdu** [comment]
the spec should be:
```
spec:
  workload:
    manifests:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: hello
        namespace: default
      spec:
        selector:
          matchLabels:
            app: hello
        template:
          metadata:
            labels:
              app: hello
          spec:
            containers:
            - command:
              - sh
              - -c
              - echo "Hello, Kubernetes!" && sleep 3600
              image: quay.io/asmacdo/busybox
              name: hello
```

but while we use clusteradm to create, it would be:
```
spec:
  workload:
    manifests:
    - apiVersion: work.open-cluster-management.io/v1
      kind: ManifestWork
      metadata:
        name: hello-work-demo
        namespace: cluster1
      spec:
        workload:
          manifests:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: hello
              namespace: default
            spec:
              selector:
                matchLabels:
                  app: hello
              template:
                metadata:
                  labels:
                    app: hello
                spec:
                  containers:
                  - command:
                    - sh
                    - -c
                    - echo "Hello, Kubernetes!" && sleep 3600
                    image: quay.io/asmacdo/busybox
                    name: hello
```

we put the whole work.yaml into the manifest filed, rather than just the `manifest` filed in the work.yaml

---

Also, we've already set the cluster and name for the manifestwork in the work.yaml, but we did that in clusteradm again. Seems that the cluster and name set in work.yaml will not be used.
