### ISSUE TITLE
no CSR to approve for cluster cluster1

### ISSUE THREAD

**Issue by Ghostwritten** [open-cluster-management-io/clusteradm#322]
I  run:
`curl -L https://raw.githubusercontent.com/open-cluster-management-io/OCM/main/solutions/setup-dev-environment/local-up.sh | bash`
`clusteradm accept --context kind-hub --clusters cluster1,cluster2 --wait`
output:
`no CSR to approve for cluster cluster1`

question:
1. How do I view the  Hub version?
2.  how to manually enable functions door "v1beta1csrapiccompatibility")? Please help with specific steps or methods.

**Comment by mikeshng** [comment]
You can probably find answer to both questions by running the following command on the Hub cluster.

```
kubectl get clustermanager -o yaml
```

As for `no CSR to approve for cluster cluster1` you will have to check the klusterlet agents on `cluster1` and see if there are some additional information. Run the following on `cluster1`

```
kubectl get klusterlet -o yaml
```

**Comment by qiujian16** [comment]
> 2. how to manually enable functions door "v1beta1csrapiccompatibility")? Please help with specific steps or methods.

This needs to add a feature gate on ClusterManager resource on hub.

```
apiVersion: operator.open-cluster-management.io/v1
kind: ClusterManager
metadata:
  name: cluster-manager
spec:
  registrationConfiguration:
    featureGates:
    - feature: V1beta1CSRAPICompatibility
       mode: Enable
    - feature: DefaultClusterSet
       mode
```
