### ISSUE TITLE
Re-init doesn't work well

### ISSUE THREAD

**Issue by aii-nozomu-oki** [open-cluster-management-io/clusteradm#383]
**Describe the bug**
A second init with different options may not change the resource.

**To Reproduce**

Run init twice with different option

1st: `clusteradm init`

2nd: `clusteradm init --feature-gates=ManagedClusterAutoApproval=true`

The featureGates of the clustermanager object are as follows

```
$ kubectl get clustermanager cluster-manager -o yaml
...
  registrationConfiguration:
    featureGates:
    - feature: DefaultClusterSet
      mode: Enable
```

**Expected behavior**

The featureGates should be as follows

```
    featureGates:
    - feature: ManagedClusterAutoApproval
      mode: Enable
    - feature: DefaultClusterSet
      mode: Enable
```

**Environment ie: OCM version, clusteradm version, Kubernetes version and provider:**

OCM: v0.12.0
clusteradm: latest(2d580956d97cbbbcfdad8dea4c5456f742ecce7c)
Kubernetes: K3s v1.27.1+k3s1

**Additional context**

Not sure if re-init is supported, but wanted to try the init again to change the feature gate.
