### ISSUE TITLE
`clusteradm join --dry-run` error and output missing manifests

### ISSUE THREAD

**Issue by EricaJ6** [open-cluster-management-io/clusteradm#416]
**Describe the bug**
Before we actually join the managed cluster to the hub, we would like to preview the resources that will be created in the managed cluster.
`clusteradm join --dry-run=true` produces below error
`Error: resource mapping not found for name: "klusterlet" namespace: "" from "local": no matches for kind "Klusterlet" in version "operator.open-cluster-management.io/v1"
ensure CRDs are installed first`
Also, with an additional `--output-file` flag, it outputs to the terminal instead of the file.

Without the `--dry-run=true` flag, it's successful without any errors.
While comparing the manifests with or without the `--dry-run` flag, with `--dry-run` flag one is missing 

```
# Copyright Contributors to the Open Cluster Management project
apiVersion: operator.open-cluster-management.io/v1
kind: Klusterlet
metadata:
  name: klusterlet
spec:
  deployOption:
    mode: Singleton
  registrationImagePullSpec: quay.io/open-cluster-management/registration:v0.13.1
  workImagePullSpec: quay.io/open-cluster-management/work:v0.13.1
  imagePullSpec: quay.io/open-cluster-management/registration-operator:v0.13.1
  clusterName: m1
  namespace: open-cluster-management-agent 
  externalServerURLs:
  
  - url: https://m1-control-plane:6443
  
  resourceRequirement:
    type: Default
  
  
    # Uncomment the following configuration lines to add hostAliases for hub api server, 
    # if the server field in your hub cluster kubeconfig is a domain name instead of an ipv4 address.
    # For example, https://xxx.yyy.zzz.
    # This configuration is used for registration-agent and work-agent to communicate with hub api server.
    # hubApiServerHostAlias:
    # ip: "1.2.3.4"
    # hostname: "xxx.yyy.zzz"

---
```

**To Reproduce**
1. `clusteradm join --hub-token $token --hub-apiserver $apiserver --cluster-name $managed_cluster_name --singleton --dry-run=true --output-file='manifests.yaml'
`
2. `clusteradm join --hub-token $token --hub-apiserver $apiserver --cluster-name $managed_cluster_name --singleton --dry-run=true
`
3. `clusteradm join --hub-token $token --hub-apiserver $apiserver --cluster-name $managed_cluster_name --singleton --output-file='manifests.yaml'
`

**Expected behavior**
With step 1, it outputs the full manifests (including Klusterlet) to the file without any error.
With step 2, it outputs the full manifests (including Klusterlet) to the terminal without any error.
With step 3, this one provides the expected behavior. 

**Environment ie: OCM version, clusteradm version, Kubernetes version and provider:**
→ clusteradm version
client		version	:v0.8.1-0-g3aea9c5
server release	version	:v1.29.2
default bundle	version	:0.13.1

**Additional context**
