### ISSUE TITLE
Add `--managed-cluster-arn` flag to the `clusteradm join` command

### ISSUE THREAD

**Issue by ahmad-ibra** [open-cluster-management-io/clusteradm#485]
**Describe the enhancement**
Currently, when joining an EKS spoke cluster to an EKS hub cluster, the managed clusters ARN is inferred from the spoke clusters kubeconfig:
https://github.com/open-cluster-management-io/clusteradm/blob/8cc04b6ea6e2b9f6e81316766f8217d69453a2a6/pkg/cmd/join/exec.go#L169

It would be nice if we could add a new flag named `--managed-cluster-arn` to the `clusteradm join` command so that we can pass in the ARN of our managed cluster as opposed to having clusteradm infer the value from the spokes kubeconfig. When this flag is set, the value passed in will be used as the `MangedClusterARN`, otherwise we can fallback to the current behavior (extracting the value from the kubeconfig).

The reason for this proposal is that when you create an eks cluster with tools like `eksctl` by default the cluster name isn't going to be its ARN. It'll be the actual name that was given to the cluster. So users will need to add an alias to their kubeconfig or manually rename the cluster in their kubeconfig which I'd like to avoid doing:
```bash
aws eks update-kubeconfig \
  --region us-west-2 \
  --name spoke-eks-test \
  --kubeconfig /Users/ahmad/Downloads/spoke-eks-test.kubeconfig \
  --alias arn:aws:eks:us-west-2:<REDACTED_ACCOUNT_ID>:cluster/spoke-eks-test
```

I'd be happy to take on this enhancement if team here doesn't have the bandwidth for it.

**Comment by mikeshng** [comment]
CC @jaswalkiranavtar @suvaanshkumar @amrcoder @jeffw17 @ramekris3163

**Comment by ahmad-ibra** [comment]
Thanks @jaswalkiranavtar , I'll go ahead and get the PR ready then!

**Comment by ahmad-ibra** [comment]
Here's the reproduction steps without setting up an alias.

1. Create the hub and spoke clusters with eksctl
```bash
eksctl create cluster --name hub-eks-test --region us-west-2 --nodes 1 --kubeconfig ~/Downloads/hub-eks-test.kubeconfig
eksctl create cluster --name spoke-eks-test --region us-west-2 --nodes 1 --kubeconfig ~/Downloads/spoke-eks-test.kubeconfig
```

This will generate kubeconfigs that look like this (note that the cluster name is set to `hub-eks-test.us-west-2.eksctl.io` and not the ARN. A similar kubeconfig is created for the spoke:
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <REDACTED>
    server: https://<REDACTED>.yl4.us-west-2.eks.amazonaws.com
  name: hub-eks-test.us-west-2.eksctl.io
contexts:
- context:
    cluster: hub-eks-test.us-west-2.eksctl.io
    user: ahmad@hub-eks-test.us-west-2.eksctl.io
  name: ahmad@hub-eks-test.us-west-2.eksctl.io
current-context: ahmad@hub-eks-test.us-west-2.eksctl.io
kind: Config
preferences: {}
users:
- name: ahmad@hub-eks-test.us-west-2.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - token
      - -i
      - hub-eks-test
      command: aws-iam-authenticator
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      - name: AWS_DEFAULT_REGION
        value: us-west-2
      provideClusterInfo: false
```

2. Follow steps 1-3 of the [joining hub and spoke with aws auth guide](https://github.com/open-cluster-management-io/ocm/tree/main/solutions/joining-hub-and-spoke-with-aws-auth)
3. Attempt step 4 without adding in the `--hub-cluster-arn` flag
```bash
clusteradm init --bundle-version latest --registration-drivers awsirsa \
--feature-gates ManagedClusterAutoApproval=true \
--auto-approved-arn-patterns "arn:aws:eks:us-west-2:745150053801:cluster/.*" --wait
flag auto-approved-arn-patterns has been set
flag bundle-version has been set
flag feature-gates has been set
flag registration-drivers has been set
flag wait has been set
        [WARNING HubApiServer check]: Hub Api Server is a domain name, maybe you should set HostAlias in klusterlet
Preflight check: HubApiServer check Passed with 1 warnings and 0 errors
Preflight check: cluster-info check Passed with 0 warnings and 0 errors
CRD successfully registered.
Error: error when creating "local": ClusterManager.operator.open-cluster-management.io "cluster-manager" is invalid: spec.registrationConfiguration.registrationDrivers[0].awsirsa.hubClusterArn: Invalid value: "hub-eks-test.us-west-2.eksctl.io": spec.registrationConfiguration.registrationDrivers[0].awsirsa.hubClusterArn in body should match '^arn:aws:eks:([a-zA-Z0-9-]+):(\d{12}):cluster/([a-zA-Z0-9-]+)$'
```
4. Run step 4 but this time specify the `--hub-cluster-arn` flag
```bash
clusteradm init --bundle-version latest --registration-drivers awsirsa \
--feature-gates ManagedClusterAutoApproval=true \
--auto-approved-arn-patterns "arn:aws:eks:us-west-2:745150053801:cluster/.*" --wait \
--hub-cluster-arn arn:aws:eks:us-west-2:745150053801:cluster/hub-eks-test
flag auto-approved-arn-patterns has been set
flag bundle-version has been set
flag feature-gates has been set
flag hub-cluster-arn has been set
flag registration-drivers has been set
flag wait has been set
        [WARNING HubApiServer check]: Hub Api Server is a domain name, maybe you should set HostAlias in klusterlet
Preflight check: HubApiServer check Passed with 1 warnings and 0 errors
Preflight check: cluster-info check Passed with 0 warnings and 0 errors
CRD successfully registered.
Registration operator is now available.
ClusterManager registration is now available.
The multicluster hub control plane has been initialized successfully!

You can now register cluster(s) to the hub control plane. Log onto those cluster(s) and run the following command:

    clusteradm join --hub-token <REDACTED> --hub-apiserver https://<REDACTED>.yl4.us-west-2.eks.amazonaws.com --wait --cluster-name <cluster_name>

Replace <cluster_name> with a cluster name of your choice. For example, cluster1.
```
4. Attempt step 5
```bash
clusteradm join --hub-token $TOKEN --hub-apiserver $HUB_API_SERVER \
--wait --cluster-name $SPOKE_CLUSTER_NAME --singleton \
--bundle-version latest --registration-auth awsirsa \
--hub-cluster-arn arn:aws:eks:$HUB_REGION:"$HUB_ACCOUNT_ID":cluster/$HUB_CLUSTER_NAME
W0515 16:34:39.563831    6409 exec.go:237] Failed looking for cluster endpoint for the registering klusterlet: configmaps "cluster-info" not found
Preflight check: HubKubeconfig check Passed with 0 warnings and 0 errors
Preflight check: DeployMode Check Passed with 0 warnings and 0 errors
Preflight check: ClusterName Check Passed with 0 warnings and 0 errors
CRD successfully registered.
Error: error when creating "local": Klusterlet.operator.open-cluster-management.io "klusterlet" is invalid: spec.registrationConfiguration.registrationDriver.awsIrsa.managedClusterArn: Invalid value: "spoke-eks-test.us-west-2.eksctl.io": spec.registrationConfiguration.registrationDriver.awsIrsa.managedClusterArn in body should match '^arn:aws:eks:([a-zA-Z0-9-]+):(\d{12}):cluster/([a-zA-Z0-9-]+)$'
```

Notice the failure due to the inferred cluster name from the kubeconfig. This is the same failure we see on the `clusteradm init` command execution, except there we have the option of using the `--hub-cluster-arn` flag.

Given this, I'm going to have a PR with the addition of the `--managed-cluster-arn` flag shortly.
